# Generated by Django 4.2.30 on 2026-04-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='ocсasion',
            new_name='occasion',
        ),
    ]
