# Generated by Django 4.2.30 on 2026-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ocсasion_bouquet_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота, см'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина, см'),
        ),
    ]
