# Generated by Django 4.2.30 on 2026-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
