# Generated by Django 4.2.30 on 2026-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_occasion_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occasion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='occasion',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
